version: '3.8'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
      - ../custom-monitors/ocpp-probe.js:/app/custom-monitors/ocpp-probe.js:ro
    ports:
      - "3001:3001"
    restart: unless-stopped
